name: Docker Build and Test

on:
  push:
    branches:
      - main
      - feature/task_restructaration
  pull_request:
    branches:
      - main
      - feature/task_restructaration

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for building multi-platform Docker images
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the Docker image from the Dockerfile
      - name: Build Docker image
        run: docker build -t ssd-project-main-image .

      # Run the Docker container
      - name: Run Docker container
        run: docker run -d -p 8080:80 --name ssd-project-main-container ssd-project-main-image

      # Wait for the container to be fully ready
      - name: Wait for Docker to be ready
        run: sleep 10  # Increase this time if your app takes longer to start

      # Test if the Docker container is responding correctly
      - name: Test Docker response
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080)
          if [ "$STATUS" == "200" ]; then
            echo "Test passed! Received HTTP 200."
          else
            echo "Test failed. Received HTTP status $STATUS."
            exit 1
          fi
